var gadgetConfig = {
    "id": "Member_Details",
    "title": "Member Details",
    "datasource": "MEMBER_DETAILS",
    "type": "batch",
    "columns": [{"name": "member_id", "type": "STRING"},
        {"name": "os_architecture", "type": "STRING"},
        {"name": "is_multi_tenant", "type": "STRING"},
        {"name": "cpu", "type": "INTEGER"},
        {"name": "cluster_instance_type", "type": "STRING"},
        {"name": "host_name","type": "STRING"},
        {"name": "allocated_IP_addresses", "type": "STRING"},
        {"name": "image_id","type": "STRING"},
        {"name": "public_IP_addresses","type": "STRING"},
        {"name": "login_port", "type": "STRING"},
        {"name": "is_64bit_os", "type": "STRING"},
        {"name": "private_IP_addresses", "type": "STRING"},
        {"name": "scaling_decision_id","type": "STRING"},
        {"name": "ram", "type": "INTEGER"}, {"name": "os_version", "type": "STRING"},
        {"name": "hypervisor","type": "STRING"},
        {"name": "os_name", "type": "STRING"}],
    "maxUpdateValue": 10,
    "chartConfig": {"chartType": "table", "xAxis": 0, "colorBasedStyle": true}
};
